#!/bin/sh

set -e
#set -x

clean_evidence_of_last_lok_run() {
  # LibreOffice might write anything to the profile directory; we don't want
  # that to persist to the next run, as it might leak into the next output
  # file.
  rm -rf "$PROFILE_DIR"
}

: "${TIMEOUT:=90}"
clean_evidence_of_last_lok_run  # Defensive programming. Should be no-op.

cp -a "$PROFILE_TEMPLATE_DIR" "$PROFILE_DIR"  # Create fresh profile directory

timeout -s KILL "$TIMEOUT" /app/convert-to-pdf-with-metadata "$1" >&2 || case "$?" in
  137)
    echo "LibreOffice timed out"
    echo "LibreOffice timed out" >&2
    ;;
  **)
    RETVAL="$?"
    echo "LibreOffice exited with code $RETVAL"
    echo "LibreOffice exited with code $RETVAL" >&2
    ;;
esac

clean_evidence_of_last_lok_run  # On success or failure
